services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zeppelin_frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev

networks:
  default:
    external: true
    name: zeppelin-forkpaulo_default
